<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Indexing, slicing and iterating
  </span>
</h2>

**One-dimensional** arrays can be indexed, sliced and iterated over, much like [lists](https://docs.python.org/3/tutorial/introduction.html#lists) and other Python sequences:

In [17]:
# example 1

import numpy as np

a = np.arange(10)**3 #1D array
print('original array:', a)

print('a[2]:', a[2]) #indexing (gets the element at position 2)
print('a[2:5]:', a[2:5]) #slicing (gets a range of elements (position 2 to 5 NOT including 5))

#modify elements
a[:6:2] = -1000 #start to position 6, set every 2nd element to -1000
print('after modification:', a)

original array: [  0   1   8  27  64 125 216 343 512 729]
a[2]: 8
a[2:5]: [ 8 27 64]
after modification: [-1000     1 -1000    27 -1000   125   216   343   512   729]


In [16]:
#example 2

import numpy as np

a = np.arange(10)**3 #1D array
print('original array:', a)

#reverse the array
print('reversed:', a[::-1])

#iteration
print('iterating:')
for element in a:
    print(element)

original array: [  0   1   8  27  64 125 216 343 512 729]
reversed: [729 512 343 216 125  64  27   8   1   0]
iterating:
0
1
8
27
64
125
216
343
512
729


In [15]:
# example 3 - more slicing examples 

import numpy as np

a = np.arange(10)**3 
print('original array:', a)

print('a[1:8:2]:', a[1:8:2]) #[start:stop:step] - 1 to 8, every 2nd element
print('a[:5]:', a[:5]) #from start to position 5
print('a[5:]:', a[5:]) #from position 5 to end
print('a[::2]:', a[::2]) #every 2nd element frrom entire array

original array: [  0   1   8  27  64 125 216 343 512 729]
a[1:8:2]: [  1  27 125 343]
a[:5]: [ 0  1  8 27 64]
a[5:]: [125 216 343 512 729]
a[::2]: [  0   8  64 216 512]


**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas.

<p style="text-align: center; font-style: italic;">
important !
</p>

`,` (comma) - separates dmensions/axes

`:` (colon) - indicates slicing within a dimension

In [29]:
# example 4

#create a 2d array
def f(x, y): #for shape (5, 4), x contains row, y contains column
    return 10*x + y 

#for each position, it calculates 10*row_index + column_index:
#row 0: 10*0+0=0, 10*0+1=1, 10*0+2=2, 10*0+3=3
#row 1: 10*1+0=10, 10*1+1=11, 10*1+2=12, 10*1+3=13

b = np.fromfunction(f,(5, 4), dtype=int) 
print('2D array:')
print(b)

#u cant try np.fromfunction(just_rows, (shape), dtype)
# np.fromfunction(just_cols, (shape), dtype)
# np.fromfunction(sum_coord, (shape), dtype)
# np.fromfunction 'says': for each position in my array, calculate the value using this formula based on its row and column position.

print('\nb[2, 3]:', b[2, 3]) #row index = 2 ; column index = 3
print('b[:, 1]:', b[:, 1]) # get all rows, but only column 1
print('b[0:5, 1]:', b[0:5, 1]) #each row in the second column
print('b[:, 1]:', b[:, 1]) #same as above
print('\nb[1:3, :]:')
print(b[1:3, :]) #second and third rows

print('\nb[::2, ::2]:')
print(b[::2, ::2]) #get every 2nd row and every 2nd column

2D array:
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

b[2, 3]: 23
b[:, 1]: [ 1 11 21 31 41]
b[0:5, 1]: [ 1 11 21 31 41]
b[:, 1]: [ 1 11 21 31 41]

b[1:3, :]:
[[10 11 12 13]
 [20 21 22 23]]

b[::2, ::2]:
[[ 0  2]
 [20 22]
 [40 42]]


In [ ]:
# example 5 slicing with ellipsis and new axis

u = np.array([[[0, 1, 2], [10, 12, 13,]], [[100, 101, 102], [110, 112, 113]]])
print('original shape:')
print(u)

print('\nu[1, ...]:')
print(u[1, ...]) #same as u[1, :, :] or u[1]

print('\nu[..., 2]:')
print(u[..., 2]) #same as u[:, :, 2]

original shape:
[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]

u[1, ...]:
[[100 101 102]
 [110 112 113]]

u[..., 2]:
[[  2  13]
 [102 113]]


<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating)