<h1 style="text-align: center; font-family: 'Geneva'; color: #f17ea1; font-size:42px;">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block; text-decoration: underline;">
     Numpy Quickstart
  </span>
</h1>

<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     The basics
  </span>
</h2>

`axes` = NumPy dimensions
- 1 axis = a list (vector)
- 2 axes = a table (matrix)
- 3 axes = a cube of data

---

*→ example 1* 

`[1, 2, 1]`

- 3D point w/ 1 axis
- 1 dimensional array, vector
- Lenght of that axis = 3 (has 3 elements inside it) 
- Shape = 3

---

*→ example 2*

`[ [1., 0., 0.],`

`[0., 1., 2.] ]`

- First axis → axis 0, vertical direction, rows
    - Lenght = 2 (2 rows inside principal list)

<br>

- Second axis → axis 1, horizontal direction, columns
    - Lenght = 3 (3 collumns, internal list has 3 numbers)

<br>

- Shape = (2,3) → 2 rows, 3 columns

---

<p style="text-align: center; font-style: italic;">
More important attributes of an ndarray object are:
</p>
<br><br>

`ndarray.ndim` = Number of axes (dimensions) of the array.<br>Example: a 2D matrix has **ndim = 2**; a vector has **ndim = 1**
<br><br>

`ndarray.shape` = The dimensions of the array, a tuple (ordered and immutable collection of elements, similar to a list, but which cannot be changed after creation) of integers showing the size along each axis. Lenght `shape` tuple = `ndim`<br>Exemple:a matrix w/ 3 rows and 4 columns has **shape = (3,4)**
<br><br>

`ndarray.size` = The total number of elements in the array. Its the product off all elements in `shape`.<br>Exemple: `shape = (3, 4)`, then **size = 12**
<br><br>

`ndarray.dtype` = The data type of the elements in the array

| dtype | What it stores | Example |
|-------|----------------|---------|
| `int32, int64` | Integers numbers | 1, -5, 100 |
| `float32, float64` | Decimals numbers | 3.14, -2.5, 0.0 |
| `bool` | Boolean Values | True, False |
| `complex` | Complex numbers | 1+2j |
| `string` | Text | "hello", "numpy" |

You can convert between dtypes using `.astype()` and you can use standard Python types or NumPy's specific types.
<br><br>

`ndarray.itemsize` = The size *in bytes* of each element of the array. It is equivalent to `ndarray.dtype.itemsize`<br>Example: `float64` has **itemsize = 8** → 64bits ÷ 8 = 8
<br><br>

`ndarray.data` = the buffer containing the actual elements of the array. In pratice, we normally dont use this attribute, we acess elements using indexing instead.

In [1]:
#example 3

import numpy as np

arr = np.array([ [1, 2, 3], [4, 5, 6] ])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print()

2
(2, 3)
6
int64
8



In [2]:
#example 4

import numpy as np

a = np.arange(15).reshape(3, 5)
a

print("Matrix:")
print(a)

print("Matrix attributes")
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print()
type(a)

b = np.array([6, 7, 8])
b

print("Vector:")
print(b)
print()

type(b)


Matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Matrix attributes
(3, 5)
2
int64
8
15

Vector:
[6 7 8]



numpy.ndarray

<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/learn)<br>🔗 [w3schools](https://www.w3schools.com/python/numpy/numpy_data_types.asp)