<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Array creation
  </span>
</h2>

There are several ways to create arrays. The most commom functionfor this, for example, is `np.array()`

In [10]:
# example 1

import numpy as np 

#creating array
a = np.array([2, 3, 4]) 

#informations abt
print(a)
print (a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

c = np.array([[5, 6, 7], [8, 9, 1]])
print(c)
print(c.dtype)

[2 3 4]
int64
[1.2 3.5 5.1]
float64
[[5 6 7]
 [8 9 1]]
int64


In [16]:
# example 2

a = np.array(1, 2, 3, 4)   #Wrong !!!

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [15]:
# example 3

#We can also create a array n specify what we want

n = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(n)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


Often, the elements of an array are originally unknown, but its size is known. Hence NumPy offers several functions to create arrays with initial placeholder content (zeros, ones or uninitializad values).

`np.zeros(shape):` Creates an array filled with zeros.<br><br>`np.ones(shape):` Creates an array filled with ones.<br><br>`np.empty(shape):` Creates an array whose initial content is random and depends on the state of the memory.<br><br>`np.full(shape, fill_value):` Creates an array filled with the specified `fill_value`. 

By default, the dtype of the created array is `float64`, but it can be specified via the key word argument `dtype`.

In [4]:
# example 4

import numpy as np

np.zeros ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# example 5

import numpy as np

np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
# example 6

import numpy as np

np.empty ((2, 2))

array([[0.00000000e+000, 1.20922412e-311],
       [1.20922412e-311, 1.20922412e-311]])

In [1]:
# example 7

import numpy as np

np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in `range`, but returns an array.

`np.arange(start, stop, step):` Creates arrays with regularly spaced values within a given interval. <u>The stop value is not included.</u>



`np.linspace(start, stop, num):` Creates arrays with a specified number of elements (`num`), spaced equally between the start and stop value. <u>The stop value is included by default.</u>

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want.

In [20]:
# example 8

import numpy as np

# array from 0 to 9 (stop value (10) not included)
a = np.arange(10)
print('arange a:', a)

# from 10 to 25, stepping by 5
b = np.arange(10, 25, 5)
print('arange b:', b)

# it accepts float arguments
c = np.arange(0, 2, 0.3)
print('arange c:', c)

arange a: [0 1 2 3 4 5 6 7 8 9]
arange b: [10 15 20]
arange c: [0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [31]:
# example 9

import numpy as np
from numpy import pi 

# 9 numbers from 0 to 2
d = np.linspace(0, 2, 9)
print('linspace d:', d)

# 5 spaced numbers from 0 to 1 excluding the endpoint
e = np.linspace(0, 1, 5, endpoint=False)
print('\nlinspace e:', e)

f = np.linspace(0, 2 * pi, 100)
print('\nlinspace f:')
print(f)

linspace d: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

linspace e: [0.  0.2 0.4 0.6 0.8]

linspace f:
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5

++ Functions:

`np.eye():` Creates a 2D identity matrix with ones on the diagonal and zeros elsewhere. It has shape (N, N)

`np.identity():` Also creates an identity matrix. It is similar to `eye` but is <u>specifically for square identity matrices.</u>

In [30]:
# example 10 

import numpy as np

# 3x3 identity matrix
g = np.eye(3)
print ('eye g:')
print(g)

h = np.eye(3, 5)
print('\neye h:')
print(h)

eye g:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

eye h:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [29]:
# example 11

import numpy as np

i = np.identity(3)
print('identity i:')
print(i)

j = np.identity(5)
print('\nidentity j:')
print(j)

identity i:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

identity j:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.diag() and np.vander() are more specialized array functions that are very useful for linear algebra and polynomial operations.

`np.diag():` Can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements. The two array creation functions can be helpful while doing linear algebra. In other words, the `diag` function has two main purposes:
1. **Extract a diagonal from a 2D array;**
2. **Create a 2D array with given diagonal.**

**AND** 

The `k` parameter:

- `k=0:` Main diagonal (default)
- `k=1:` Diagonal one above main
- `k=-1:` Diagonal one below main
- `k=2:` Two above main, etc.

In [28]:
# example 12 , extract a diagonal from a 2D array

import numpy as np

# create a 2D matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Original matrix:')
print(matrix)

# extract the main diagonal
main_diag = np.diag(matrix)
print('\nMain diagonal:', main_diag)

# extract diagonal above main k=1
diag_above = np.diag(matrix, k=1)
print('\nDiagonal k=1:', diag_above)

# extract diagonal below main
diag_below = np.diag(matrix, k=-1)
print('\nDiagonal k=-1:', diag_below)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Main diagonal: [1 5 9]

Diagonal k=1: [2 6]

Diagonal k=-1: [4 8]


In [27]:
# example 13 , create a 2D array with given diagonal

import numpy as np

diagonal_elements = np.array ([1, 2, 3])
diag_matrix = np.diag(diagonal_elements)
print('Diagonal matrix:')
print(diag_matrix)

# with off-diagonals

off_diag_matrix = np.diag([1, 2, 3], k=1)
print('\nOff-diagonal matrix (k=1):')
print(off_diag_matrix)

Diagonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Off-diagonal matrix (k=1):
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


`np.vander()`, vander (x,n) defines a Vandermonde matrix as a 2D NumPy array, is used for <u>polynomial fitting.</u> Each column is a decreasing power of the input 1D array or list or tuple (`x`) where the highest polynomial order is **n-1**.

Syntax: `np.vander(x, N=None, increasing=False)`

- `x:` 1D input array.
- `N:` Number of columns in output.
- `increasing:` If true, powers increase left to right.

In [37]:
# example 14 

# create vandermonde matrix

k = np.array([1, 2, 3, 4])
vander_matrix = np.vander(k)
print('x =', k)
print('\nVandermonde matrix (decresing powers):')
print(vander_matrix)

# with increasing = true

vander_inc = np.vander(k, increasing=True)
print('\nVandermonde matrix (increasing powers):')
print(vander_inc)

x = [1 2 3 4]

Vandermonde matrix (decresing powers):
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]

Vandermonde matrix (increasing powers):
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Printing  arrays
  </span>
</h2>

lalala

<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/learn)