<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Array creation
  </span>
</h2>

There are several ways to create arrays. The most commom functionfor this, for example, is `np.array()`

In [10]:
# example 1

import numpy as np 

#creating array
a = np.array([2, 3, 4]) 

#informations abt
print(a)
print (a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

c = np.array([[5, 6, 7], [8, 9, 1]])
print(c)
print(c.dtype)

[2 3 4]
int64
[1.2 3.5 5.1]
float64
[[5 6 7]
 [8 9 1]]
int64


In [16]:
# example 2

a = np.array(1, 2, 3, 4)   #Wrong !!!

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [15]:
# example 3

#We can also create a array n specify what we want

n = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
print(n)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


Often, the elements of an array are originally unknown, but its size is known. Numpy offers several several functions to create arrays with initial content (zeros, ones or uninitializad values)

<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Printing  arrays
  </span>
</h2>

lalala

<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/learn)