<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Basic operations
  </span>
</h2>

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [1]:
# example 1

import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print('a + b =', a+b)
print('a - b =', a-b)
print('a * b =', a*b)
print('a / b =', a/b)
print('a ** 2 =', a**2)

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]


In [66]:
# example 2

import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b

print('c =', c)
print('a ** 2 =', a**20)
print('a < 35 =', a<35)

c = [20 29 38 47]
a ** 2 = [-2101438300051996672 -4356359181443268608  1152921504606846976
  5474894590040342528]
a < 35 = [ True  True False False]


Matrix multiplication is <u>**not**</u> the same as elementwise multiplication. The matrix product can be perfomed using the `@`, `np.dot()` or `.dot()` operator.  

<br>

<p style="text-align: center; font-style: italic;">
important rules !
</p>

- For `a @ b`, the number of columns in a must equal number of rows in b

- If a is (mxn) and b is (nxp), result will be (mxp)

In [12]:
# example 3

import numpy as np

u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])

print('u @ v:')
print(u@v)

print('\nnp.dot:')
print(np.dot(u,v))

print('\n.dot:')
print(u.dot(v))

u @ v:
[[19 22]
 [43 50]]

np.dot:
[[19 22]
 [43 50]]

.dot:
[[19 22]
 [43 50]]


In [ ]:
# the calculous !!

#  u = [1, 2], [3, 4]
# v = [5, 6], [7, 8]

# Result[0,0] = (1×5) + (2×7) = 5 + 14 = 19
# Result[0,1] = (1×6) + (2×8) = 6 + 16 = 22
#Result[1,0] = (3×5) + (4×7) = 15 + 28 = 43
# Result[1,1] = (3×6) + (4×8) = 18 + 32 = 50

In [13]:
# example 4 - compare w/ elementwise multiplication

import numpy as np

u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])

print('u * v:')
print(u*v)

print('\nu @ v:')
print(u@v)

u * v:
[[ 5 12]
 [21 32]]

u @ v:
[[19 22]
 [43 50]]


Some operations act in place to modify an existing array rather than create a new one.

- `+=` Add and assign
- `-=` Subtract and assign
- `*=` Multiply and assign
- `//=` Divide and assign

In-place operations changes the original array, are faster, use less memory (but lose the original) and are great for performance with large data.

Regular operations creates a new array, you keep the original data.

In [19]:
# example 5

import numpy as np

f = np.array([1, 2, 3, 4])

f +=2
print('+=2:', f)

f *=3
print('*=3:', f)

f -=1
print('-=1:', f)

f //=2
print('//=2:', f)

+=2: [3 4 5 6]
*=3: [ 9 12 15 18]
-=1: [ 8 11 14 17]
//=2: [4 5 7 8]


In [65]:
# example 6 - WATCH OUT !!!

import numpy as np 

k = np.array([1, 2, 3])
b = k 

b +=10 #this modify BOTH arrays !!!
print('k:', k) #changed
print('b:', b)

k: [11 12 13]
b: [11 12 13]


In [64]:
# example 7 - solution !! 

# use .copy()

import numpy as np 

k = np.array([1, 2, 3])
b = k.copy() #creates copy

b +=10
print('k:', k) #safe !!
print('b:', b)

k: [1 2 3]
b: [11 12 13]


In [63]:
# example 8

import numpy as np

rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random ((2, 3))

a *=3
print('a *= :')
print (a)

b += a
print('\nb += a:')
print(b)

a *= :
[[3 3 3]
 [3 3 3]]

b += a:
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


Many <u>unary operations</u>, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

Unary operations = Operations that work on <u>**one**</u> array and give you back a **single result** or **new transformed array.**

- `.sum():` add everything, all numbers togheter
- `.mean():` find the average, add al numbers an divide by how many they are
- `.min():` find the smallest number
- `.max():` find the biggest number
- `.std():` are numbers close togheter or far apart? how spread out are the numbers? (std ≈ 1-2 = very similar ; std ≈ 10-15 = quite different ; std ≈ 20+ = very different)

In [62]:
# example 9

import numpy as np

h = np.array([150, 200, 175, 300, 250])

total = h.sum()
print('sum:', total) #150+200+175+300+250

av_h = h.mean()
print('avarege:', av_h) #(150+200+175+300+250)/5

min_h = h.min()
print('min:', min_h)

max_h = h.max()
print('max:', max_h)

print('---')

a = np.array([85, 87, 86, 88, 84]) #close togheter
b = np.array([60, 95, 75, 100, 70]) #far apart

print('a spread:', a.std())
print('b spread:', b.std())

sum: 1075
avarege: 215.0
min: 150
max: 300
---
a spread: 1.4142135623730951
b spread: 15.165750888103101


In [61]:
# example 10

import numpy as np 

m = np.arange(15).reshape(3, 5)
print('m:')
print(m)

print('sum of each column:', m.sum(axis=0))

print('min of each row:', m.min(axis=1))

m:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
sum of each column: [15 18 21 24 27]
min of each row: [ 0  5 10]


<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Universal functions
  </span>
</h2>


NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (`ufunc`). Within NumPy, these functions operate elementwise on an array, producing an array as output.
This means thtat universal functions are math functions that work on every element in an array !

- `np.exp():` exponential function
- `np.sqrt():` square root
- `np.add():` elementwise addition
- `np.square():` square
- `np.log():` logarithm
- `np.sin():` sin
- `np.cos():` cos <br> ...

In [ ]:
# example 1

import numpy as np

wonderful = np.array([0, 1, 2])
print('wonderful original:', wonderful)

resultexp = np.exp(wonderful)
print('afer np.exp(wonderful):', resultexp) #e^0, e^1, e^2

resultsqrt = np.sqrt(wonderful)
print('after np.sqrt(wonderful):', resultsqrt) #√0, √1, √2

print('---')

m = np.array([0, 1, 2])
n = np.array([2, -1, 4])

print('array m:', m)
print('array n:', n)

resultmn = np.add(m, n)
print('after np.add(m, n):', resultmn) #0+2, 1+(-1), 2+4

wonderful original: [0 1 2]
afer np.exp(wonderful): [1.         2.71828183 7.3890561 ]
after np.sqrt(wonderful): [0.         1.         1.41421356]
---
array m: [0 1 2]
array n: [ 2 -1  4]
after np.add(m, n): [2 0 6]


In [73]:
# example 3

y = np.array([1, 4, 9, 16])

print('original array:', y)
print('square:', np.square(y))
print('logarithm:', np.log(y))

angles = np.array([0, 30, 45, 180])
radians = np.radians(angles) #convert to radians

print('angles:', angles)
print('sin:', np.sin(radians))
print('cos:', np.cos(radians))

original array: [ 1  4  9 16]
square: [  1  16  81 256]
logarithm: [0.         1.38629436 2.19722458 2.77258872]
angles: [  0  30  45 180]
sin: [0.00000000e+00 5.00000000e-01 7.07106781e-01 1.22464680e-16]
cos: [ 1.          0.8660254   0.70710678 -1.        ]


See also !!

- `.argmax(), .argmin():` find position of highest/lowest
- `.sort():` sort the array
- `.argsort():` get sorting order
- `.nonzero():` find non-zero elements
- `.cumsum():` cumulative sum
- `.prod():` multiply all elements
- `.diff():` differences between elements
- `.clip():` limit value range
- `.where():` conditional selection
- `.round():` round numbers
- `.transpose():` flip rows/columns
- `.all():` check if all are true
- `.any():` check if any are true
- `.bincount():` count occurrences
- `.vextorize():` make any function work on arrays

<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/devdocs/user/quickstart.html#basic-operations)