<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Basic operations
  </span>
</h2>

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [1]:
# example 1

import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print('a + b =', a+b)
print('a - b =', a-b)
print('a * b =', a*b)
print('a / b =', a/b)
print('a ** 2 =', a**2)

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]


In [7]:
# example 2

a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b

print('c =', c)
print('a ** 2 =', a**20)
print('a < 35 =', a<35)

c = [20 29 38 47]
a ** 2 = [-2101438300051996672 -4356359181443268608  1152921504606846976
  5474894590040342528]
a < 35 = [ True  True False False]


Matrix multiplication is <u>**not**</u> the same as elementwise multiplication. The matrix product can be perfomed using the `@`, `np.dot()` or `.dot()` operator.  

<br>

<p style="text-align: center; font-style: italic;">
important rules !
</p>

- For `a @ b`, the number of columns in a must equal number of rows in b

- If a is (mxn) and b is (nxp), result will be (mxp)

In [12]:
# example 3

import numpy as np

u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])

print('u @ v:')
print(u@v)

print('\nnp.dot:')
print(np.dot(u,v))

print('\n.dot:')
print(u.dot(v))

u @ v:
[[19 22]
 [43 50]]

np.dot:
[[19 22]
 [43 50]]

.dot:
[[19 22]
 [43 50]]


In [ ]:
# the calculous !!

#  u = [1, 2], [3, 4]
# v = [5, 6], [7, 8]

# Result[0,0] = (1×5) + (2×7) = 5 + 14 = 19
# Result[0,1] = (1×6) + (2×8) = 6 + 16 = 22
#Result[1,0] = (3×5) + (4×7) = 15 + 28 = 43
# Result[1,1] = (3×6) + (4×8) = 18 + 32 = 50

In [13]:
# example 4 - compare w/ elementwise multiplication

import numpy as np

u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])

print('u * v:')
print(u*v)

print('\nu @ v:')
print(u@v)

u * v:
[[ 5 12]
 [21 32]]

u @ v:
[[19 22]
 [43 50]]


Some operations act in place to modify an existing array rather than create a new one.

- `+=` Add and assign
- `-=` Subtract and assign
- `*=` Multiply and assign
- `//=` Divide and assign

In-place operations changes the original array, are faster, use less memory (but lose the original) and are great for performance with large data.

Regular operations creates a new array, you keep the original data.

In [19]:
# example 5

import numpy as np

f = np.array([1, 2, 3, 4])

f +=2
print('+=2:', f)

f *=3
print('*=3:', f)

f -=1
print('-=1:', f)

f //=2
print('//=2:', f)

+=2: [3 4 5 6]
*=3: [ 9 12 15 18]
-=1: [ 8 11 14 17]
//=2: [4 5 7 8]


In [23]:
# example 6 - WATCH OUT !!!

k = np.array([1, 2, 3])
b = k 

b +=10 #this modify BOTH arrays !!!
print('k:', k) #changed
print('b:', b)

k: [11 12 13]
b: [11 12 13]


In [24]:
# example 7 - solution !! 

# use .copy()

k = np.array([1, 2, 3])
b = k.copy() #creates copy

b +=10
print('k:', k) #safe !!
print('b:', b)

k: [1 2 3]
b: [11 12 13]


In [29]:
# example 8

rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random ((2, 3))

a *=3
print('a *= :')
print (a)

b += a
print('\nb += a:')
print(b)

a *= :
[[3 3 3]
 [3 3 3]]

b += a:
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


<h2 style="text-align: center; font-style:italic; font-family: 'Geneva'; color: #f17ea1; font-size:35px">
  <span style="background-color: #facef9; padding: 2px 10px; border-radius: 6px; display: inline-block;">
     Universal functions
  </span>
</h2>

lalal

<h2 style="text-align: left; font-family: 'Geneva'; color: #facef9; font-size:30px">
  <span style="background-color: #f17ea1; padding: 2px 10px; border-radius: 6px; display: inline-block;">
    Referencess
  </span>
</h2>


🔗 [NumPy Learn](https://numpy.org/devdocs/user/quickstart.html#basic-operations)